version: "3.3"

services:
  postgres:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      - POSTGRES_USER=userpostgres # Register - Server Bölümünde Username  Kısmı için
      - POSTGRES_PASSWORD=pwpostgres # Register - Server Bölümünde Password Kısmı için
    ports:
      - "5432:5432"
    volumes:
      - ./sqldata:/var/lib/postgresql/data
    restart: unless-stopped

  pg-admin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=name@mail.com # Burası pgAdmin sayfasında ki kullanıcı adınız olacak.
      - PGADMIN_DEFAULT_PASSWORD=admin #Burası pgAdmin sayfasında ki kullanıcı parolanız olacak.
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"
    restart: always

volumes:
  sqldata:
